version: 2.1

orbs:
  cypress: cypress-io/cypress@3.3.1

jobs:
  start-server:
    docker:
      - image: cypress/base:current
    steps:
      - checkout
      - run:
          name: Install Deps
          command: npm install
      - run:
          name: build
          command: npm run build
  deploy-to-staging:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Deploy to staging
          command: |
            echo "Deploying to staging"
            curl $RENDER_STAGING_DEPLOYHOOK
  deploy-to-production:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: Deploy to production
          command: |
            echo "Deploying to production"
            curl $RENDER_PRODUCTION_DEPLOYHOOK

workflows:
  run-tests-and-stage-then-hold-for-production:
    jobs:
      - start-server
      - cypress/run:
          name: run-component-tests
          cypress-command: npx cypress run --component
      - deploy-to-staging:
          requires:
            - run-component-tests
          filters:
            branches:
              only: main
      - hold:
          type: approval
          requires:
            - deploy-to-staging
      - deploy-to-production:
          requires:
            - hold
          filters:
            branches:
              only: main